# Generated by Django 5.0.7 on 2024-07-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_offeritem_delete_customer_remove_offer_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='client_address',
        ),
        migrations.AddField(
            model_name='offer',
            name='customer_address',
            field=models.CharField(default=112, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='service_name',
            field=models.CharField(default=33, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='OfferItem',
        ),
    ]
